version: '3.3'

services:
  project_name-php:
    image:       devilbox/php-fpm:8.1-work-0.123
    working_dir: /application
    environment:
      APP_ENV:  'local'
      TIMEZONE: 'Asia/Almaty'
    volumes:
      - ${PWD}/backend:/application
    ports:
      - 9000
    restart:     unless-stopped

  project_name-nginx:
    image: nginx
    ports:
      - 8888:80
    volumes:
      - ${PWD}/configurations/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ${PWD}/configurations/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PWD}/backend:/application

  project_name-postgres:
    image:   postgres:13
    restart: always
    environment:
      POSTGRES_USER:     'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB:       'postgres'
      SCHEMA:            'public'

    ports:
      - 54133:5432
    volumes:
      - ${PWD}/configurations/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ${PWD}/postgres-data:/var/lib/postgresql/data
